AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository for ecr-push-lab - Kakwezi Peace

Parameters:
  ProjectName:
    Type: String
    Default: ecr-push-lab

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${ProjectName}-repo'
      ImageTagMutability: IMMUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": { "type": "expire" }
              }
            ]
          }
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Owner
          Value: Kakwezi-Peace
        - Key: Environment
          Value: production

Outputs:
  ECRRepositoryURI:
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProjectName}-repo'
    Export:
      Name: !Sub '${ProjectName}-ecr-uri'
